spring:
  application:
    name: agent
  # 开启虚拟线程
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/travel_agent
    username: postgres
    password: LuQingJia!@#$%^&*()_+040126

  ai:
    vectorstore:
      pgvector:
        schema-name: rag



